### ISSUE TITLE
这个怎么使用啊?

### ISSUE THREAD

**Issue by roger125** [QS20199/AutoScroll#1]
下载下来的是个.zip文件, 而chrome的插件是.crx后缀的, 然后我改为AutoScroll-master.crx, 尝试添加至插件页面, 提示无效....到底该如何安装呢?

谢谢.

**Comment by QS20199** [comment]
解压zip, 把解压后的`AutoScroll-master`目录拖进插件页面就可以了

**Comment by roger125** [comment]
好的, 已按照你说的, 安装试用, 但发现速度实在太慢, 最快的拖动到最右边, 依旧不是我期望的速度, 我可以修改下参数值吗?

**Comment by QS20199** [comment]
可以的, 打开`.\assets\js\eventPage.js`
修改第17行

``` js
count += (ret.speed || 30) / 100;
```

把最后面的100改小即可增大速度

**Comment by roger125** [comment]
好的, 已按照你说的修改为1, 刚才试用了一下, 速度确实快了很多, 最小值是"1"吗? 还可以比"1"更快吗? 因为当前的场景是在facebook.com的news feed/group里面的discussion, 滚动条一直下滑, 直到group的最开始创建的时候. 在持续下滑的过程中, 感觉后续滚动条的每次下滑之间的间隙不是很大(或者说看着很小, 越来越小), 还是我眼睛的错觉?

**Comment by QS20199** [comment]
可以更小, 你也可以把除法换成乘法, 这样就非常快了

``` js
count += (ret.speed || 30) * 100
```

**Comment by roger125** [comment]
好的, 已试用, 确实蛮快的; 

还有最后一个问题(或许应该说是chrome本身的设置问题)
, 由于其不是从官方webstore下载的插件, 而是开发者模式安装本地文件夹的方式安装上去的, 所以每次启动chrome之后, 右上角都会提示停用该插件, 每天都要多点击一次, 在一直使用该插件的前提下, 有什么好的解决方案吗?

**Comment by QS20199** [comment]
由于插件未经Google验证, 所以弹这个提示是正常的. 我目前都是每次点一下, 没有查到解决方案

**Comment by roger125** [comment]
http://www.javatang.com/archives/2015/04/26/34591223.html, 根据这里的方法, 我已经完美解决该问题了, 一直试到该文中的最后一行说明才解决..你可以试试哦..

**Comment by roger125** [comment]
http://www.javatang.com/archives/2015/04/26/34591223.html 这里介绍的这种方法几个月前试过, 是可行的; 但现在更新至最新版本chrome[Version 54.0.2840.87 m (64-bit)]之后, 由于chrome重装, 第三方插件路径的变化, 导致需要再次尝试, 但尝试多次, 却看到无效了...这是为何啊? 难道你上面说的没有找到解决方案就是因为此一方法有时会失效吗?

**Comment by QS20199** [comment]
没有去尝试这个方法, 嫌太麻烦...
我的是下了个gmail插件, 让chrome长期留存后台, 就不会每次打开就有这个提示了
